[[news]]
date = "2025-09"
content = "Started Master's at Tsinghua University (Medicine & Engineering)"

[[news]]
date = "2025"
content = "iGEM International Gold Medal (Team Advisor) & Silver Medal (Team Instructor)"

[[news]]
date = "2025"
content = "Paper published in <i>Translational Oncology</i> (Co-first author): patient-derived xenograft models in multiple myeloma"

[[news]]
date = "2024"
content = "iGEM International Gold Medal (Team Leader); 'Challenge Cup' National Bronze Award"

[[news]]
date = "2023"
content = "Two posters presented at ASH Annual Meeting (1st Author)"

[[news]]
date = "2023"
content = "Visiting Student, Westlake University (Hematopoietic stem cell research)"

[[news]]
date = "2023"
content = "Academic Program, University of Cambridge (Machine Learning & Computer Vision)"
