[[news]]
date = "2025.09"
content = "进入清华大学攻读硕士学位（医学与工程交叉学科）"

[[news]]
date = "2025"
content = "iGEM 国际金奖（指导老师）& 国际银奖（带队教练）"

[[news]]
date = "2025"
content = "论文发表于 <i>Translational Oncology</i>（共同第一作者）：多发性骨髓瘤患者来源异种移植模型建立"

[[news]]
date = "2024"
content = "iGEM 国际金奖（队长）；「挑战杯」全国铜奖"

[[news]]
date = "2023"
content = "两篇海报在 ASH 年会上展示（第一作者）"

[[news]]
date = "2023"
content = "西湖大学访问学生（造血干细胞研究）"

[[news]]
date = "2023"
content = "剑桥大学学术项目（机器学习与计算机视觉）"
